version: '3.4'

services:
  db:
    image: "mysql:5.5"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_CLIENT_PASSWORD: ${MYSQL_CLIENT_PASSWORD}
      MYSQL_READER_PASSWORD: ${MYSQL_READER_PASSWORD}
    volumes:
      - ./database:/database
      - mysql-data:/var/lib/mysql # persist db
    networks:
      - lords-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  ape:
    image: "i386/ubuntu:17.10"
    ports:
      - "6969:6969"
    volumes:
      - ./ape_scripts:/ape_scripts
    command: bash -c "cd /ape_scripts/bin ; chmod 755 ./aped ; ./aped"
    networks:
      - lords-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    image: 127.0.0.1:5000/demo # local registry
    build: .
    ports:
      - "80:80"
    environment:
      LORDS_DOMAIN: ${LORDS_DOMAIN}
      REVISION: ${REVISION}
      MYSQL_CLIENT_PASSWORD: ${MYSQL_CLIENT_PASSWORD}
      MYSQL_READER_PASSWORD: ${MYSQL_READER_PASSWORD}
    volumes:
      - ./web:/var/www/html
      - ./log:/var/log/apache2
    networks:
      - lords-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  ai:
    image: "java:7"
    ports:
      - "5600" # not shared to host
    volumes:
      - ./deployment:/deployment
      - ./ai:/ai
    command: bash -c "cd /deployment ; chmod 755 ./deploy_ai.sh ; ./deploy_ai.sh"
    networks:
      - lords-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql-data:

networks:
  lords-network:
    driver: overlay
    attachable: true
